import os
import requests
from google import genai
from dotenv import load_dotenv

load_dotenv()

# Configure Gemini API using the new google-genai structure
API_KEY = os.getenv("GEMINI_API_KEY")
if API_KEY:
    client = genai.Client(api_key=API_KEY)
else:
    client = None

def get_human_address(lat, lng):
    """
    Utility to convert coordinates to a human-readable address via Nominatim.
    """
    try:
        url = f"https://nominatim.openstreetmap.org/reverse?format=json&lat={lat}&lon={lng}"
        headers = {"User-Agent": "CivicIssueTracker/1.0"}
        res = requests.get(url, headers=headers, timeout=5)
        if res.status_code == 200:
            return res.json().get("display_name", f"Lat: {lat}, Lng: {lng}")
    except Exception:
        pass
    return f"Lat: {lat}, Lng: {lng}"

def generate_critical_notice_via_microservice(days_window: int = 90) -> dict:
    """
    Acts as a microservice communication layer. Hits the Hotspot Detection service (Port 8002)
    to fetch infrastructure failure probabilities. If a CRITICAL risk exists, it utilizes 
    Google Gemini to auto-draft an urgent administrative memo.
    """
    if not client:
        return {"error": "GEMINI_API_KEY not configured. Cannot generate notice."}

    try:
        # Ping the neighboring Microservice (Hotspot Detection) to get raw ML bounds
        res = requests.get(f"http://localhost:8002/api/predict/infrastructure?days={days_window}")
        if res.status_code != 200:
            return {"error": "Hotspot Detection Service (8002) is offline or unreachable."}
            
        predictions = res.json().get("predictions", [])
    except Exception as e:
        return {"error": f"Failed to connect to Hotspot Microservice: {e}"}

    critical_zones = [p for p in predictions if p.get("trend_status") == "CRITICAL"]
    if not critical_zones:
        return {"message": "No critical zones detected currently across the jurisdiction."}

    # Grab the most severe critical zone to alert the administrators
    top_critical_zone = max(critical_zones, key=lambda x: x["risk_score"])
    
    # Extract data for Gemini prompt
    days = top_critical_zone.get("predicted_failure_days", "Unknown")
    score = round(top_critical_zone.get("risk_score", 0), 2)
    issues = ", ".join(top_critical_zone.get("primary_issues", ["Multiple"]))
    lat = top_critical_zone.get("zone", {}).get("lat", "N/A")
    lng = top_critical_zone.get("zone", {}).get("lng", "N/A")
    radius = top_critical_zone.get("radius_km", 0.5)

    # 📍 NEW: Reverse Geocoding for human-readable intelligence
    human_address = get_human_address(lat, lng)

    # Determine the target department based on primary issues
    issue_to_dept = {
        "Pothole": "road",
        "Water": "water-supply",
        "Sewage": "drainage",
        "Garbage": "sanitation",
        "Waste": "waste-management",
        "Streetlight": "streetlight",
        "Light": "streetlight",
        "Drain": "drainage",
        "Toilet": "toilet",
        "Park": "park"
    }
    
    # Default to general if no match found
    target_dept = "general"
    for issue in top_critical_zone.get("primary_issues", []):
        for key, dept in issue_to_dept.items():
            if key.lower() in issue.lower():
                target_dept = dept
                break
        if target_dept != "general": break

    prompt = f"""
    You are an automated Civic AI Assistant for the Bandra Municipal Corporation (BMC). 
    A predictive ML algorithm has detected a CRITICAL infrastructure collapse risk that requires immediate government intervention. 

    Data Output:
    - Expected System Failure: Within {days} days
    - Risk Severity Index: {score} / 100
    - Root Causes: {issues}
    - Geographic Zone: {human_address}
    - Technical Coordinates: Lat {lat}, Lng {lng}
    - Impact Radius: Approximately {radius} km coverage area
    - Affected Department: {target_dept.upper()}

    Draft an official, professional, and urgent "BMC EMERGENCY INFRASTRUCTURE ALERT".
    The memo should follow a professional government format:
    1. Header: "BANDRA MUNICIPAL CORPORATION - EMERGENCY ACTION MEMORANDUM"
    2. Section: "TO: DEPARTMENT HEAD OF {target_dept.upper()}"
    3. Section: "SUBJECT: URGENT ACTION REQUIRED - PREDICTIVE FAILURE ALERT"
    4. Body: 3 structured paragraphs explaining the risk, the specific address/landmark, the impact radius/coverage, and the immediate mitigation required. 
    5. Footer: "Generated by BMC Unified Intelligence Engine - Gemini Pro"

    Format the response using clean, modern HTML (with inline styles for a premium look, e.g., <div style="...">, <b>, <p>, <ul>). 
    Use a subtle red/gray color palette. Do not include markdown code block syntax.
    """

    try:
        response = client.models.generate_content(
            model='gemini-flash-latest',
            contents=prompt
        )
        memo = response.text.replace("```html", "").replace("```", "").strip()
        
        return {
            "zone_data": top_critical_zone,
            "llm_draft_html": memo,
            "target_department": target_dept
        }
    except Exception as e:
        return {"error": f"Failed to generate notice via LLM: {str(e)}"}
